### ISSUE TITLE
why do you obfuscated code of all "dist/main.js" ?

### ISSUE THREAD

**Issue by RayTraceX** [amengede/webgpu-for-beginners#1]
why do you obfuscated code of all "dist/main.js" ? 

and where I could see the formatted original code ?

**Comment by Atlas16A** [comment]
dist is distribution, its the compiled version from im guessing webpack based off the looks of it
just ignore the dist folder

**Comment by amengede** [comment]
Yes that's correct, webpack bundles everything together and generates main.js. All of the original code is in the src folder. Hope that helps! 🙂
